# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastrar Usuário.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadUsuarioWindow(object):
    def setupUi(self, cadUsuarioWindow):
        cadUsuarioWindow.setObjectName("cadUsuarioWindow")
        cadUsuarioWindow.resize(800, 600)
        cadUsuarioWindow.setMinimumSize(QtCore.QSize(800, 600))
        cadUsuarioWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(cadUsuarioWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-10, 0, 461, 621))
        self.frame_2.setStyleSheet("background-color: rgb(240, 246, 247);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.cadasterButton = QtWidgets.QPushButton(self.frame_2)
        self.cadasterButton.setGeometry(QtCore.QRect(80, 510, 81, 41))
        self.cadasterButton.setStyleSheet("QPushButton{\n"
"    border-radius: 20px;\n"
"    background-color: rgb(82, 175, 204);\n"
"}")
        self.cadasterButton.setObjectName("cadasterButton")
        self.goBackButton = QtWidgets.QPushButton(self.frame_2)
        self.goBackButton.setGeometry(QtCore.QRect(230, 510, 81, 41))
        self.goBackButton.setStyleSheet("QPushButton{\n"
"    border-radius: 20px;\n"
"    background-color: rgb(48, 50, 51);\n"
"    color: rgb(240, 246, 247);\n"
"}")
        self.goBackButton.setObjectName("goBackButton")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(30, 230, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(30, 290, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(30, 350, 61, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(30, 410, 61, 16))
        self.label_8.setObjectName("label_8")
        self.nomeEdit = QtWidgets.QLineEdit(self.frame_2)
        self.nomeEdit.setGeometry(QtCore.QRect(30, 70, 261, 20))
        self.nomeEdit.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.nomeEdit.setObjectName("nomeEdit")
        self.cpfEdit = QtWidgets.QLineEdit(self.frame_2)
        self.cpfEdit.setGeometry(QtCore.QRect(30, 130, 113, 20))
        self.cpfEdit.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.cpfEdit.setObjectName("cpfEdit")
        self.emailEdit = QtWidgets.QLineEdit(self.frame_2)
        self.emailEdit.setGeometry(QtCore.QRect(30, 190, 121, 20))
        self.emailEdit.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.emailEdit.setObjectName("emailEdit")
        self.registerEdit = QtWidgets.QLineEdit(self.frame_2)
        self.registerEdit.setGeometry(QtCore.QRect(30, 250, 113, 20))
        self.registerEdit.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.registerEdit.setObjectName("registerEdit")
        self.trabLocalEdit = QtWidgets.QLineEdit(self.frame_2)
        self.trabLocalEdit.setGeometry(QtCore.QRect(30, 310, 261, 20))
        self.trabLocalEdit.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.trabLocalEdit.setObjectName("trabLocalEdit")
        self.userEdit = QtWidgets.QLineEdit(self.frame_2)
        self.userEdit.setGeometry(QtCore.QRect(30, 370, 113, 20))
        self.userEdit.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.userEdit.setObjectName("userEdit")
        self.senhaEdit = QtWidgets.QLineEdit(self.frame_2)
        self.senhaEdit.setGeometry(QtCore.QRect(30, 430, 113, 20))
        self.senhaEdit.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.senhaEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senhaEdit.setObjectName("senhaEdit")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(440, -10, 401, 611))
        self.frame.setStyleSheet("background-color: rgb(82, 175, 204);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 180, 271, 31))
        self.label.setStyleSheet("color: rgb(240, 246, 247);\n"
"font: 22pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        cadUsuarioWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(cadUsuarioWindow)
        QtCore.QMetaObject.connectSlotsByName(cadUsuarioWindow)

    def retranslateUi(self, cadUsuarioWindow):
        _translate = QtCore.QCoreApplication.translate
        cadUsuarioWindow.setWindowTitle(_translate("cadUsuarioWindow", "MainWindow"))
        self.cadasterButton.setText(_translate("cadUsuarioWindow", "Cadastrar"))
        self.goBackButton.setText(_translate("cadUsuarioWindow", "Voltar"))
        self.label_2.setText(_translate("cadUsuarioWindow", "Nome"))
        self.label_3.setText(_translate("cadUsuarioWindow", "CPF"))
        self.label_4.setText(_translate("cadUsuarioWindow", "Email"))
        self.label_5.setText(_translate("cadUsuarioWindow", "N° Registro"))
        self.label_6.setText(_translate("cadUsuarioWindow", "Local de Trabalho"))
        self.label_7.setText(_translate("cadUsuarioWindow", "Usuário"))
        self.label_8.setText(_translate("cadUsuarioWindow", "Senha"))
        self.label.setText(_translate("cadUsuarioWindow", "Cadastre seu usuário"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cadUsuarioWindow = QtWidgets.QMainWindow()
    ui = Ui_cadUsuarioWindow()
    ui.setupUi(cadUsuarioWindow)
    cadUsuarioWindow.show()
    sys.exit(app.exec_())
