# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastrar Leito.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadastrarLeito(object):
    def setupUi(self, CadastrarLeito):
        CadastrarLeito.setObjectName("CadastrarLeito")
        CadastrarLeito.resize(800, 405)
        CadastrarLeito.setMinimumSize(QtCore.QSize(800, 405))
        CadastrarLeito.setMaximumSize(QtCore.QSize(800, 405))
        self.centralwidget = QtWidgets.QWidget(CadastrarLeito)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, -51, 441, 661))
        self.frame_2.setStyleSheet("\n"
"background-color: rgb(240, 246, 247);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.cadasterButton = QtWidgets.QPushButton(self.frame_2)
        self.cadasterButton.setGeometry(QtCore.QRect(60, 310, 101, 41))
        self.cadasterButton.setStyleSheet("QPushButton{\n"
"    border-radius: 20px;\n"
"    background-color: rgb(82, 175, 204);\n"
"}\n"
"")
        self.cadasterButton.setObjectName("cadasterButton")
        self.goBackButton = QtWidgets.QPushButton(self.frame_2)
        self.goBackButton.setGeometry(QtCore.QRect(230, 310, 101, 41))
        self.goBackButton.setStyleSheet("QPushButton{\n"
"    border-radius: 20px;\n"
"    background-color: rgb(48, 50, 51);\n"
"    color: rgb(240, 246, 247);\n"
"}")
        self.goBackButton.setObjectName("goBackButton")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(40, 140, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(40, 200, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(210, 170, 71, 16))
        self.label_3.setObjectName("label_3")
        self.leitoEdit = QtWidgets.QLineEdit(self.frame_2)
        self.leitoEdit.setGeometry(QtCore.QRect(40, 160, 113, 20))
        self.leitoEdit.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.leitoEdit.setObjectName("leitoEdit")
        self.equipEdit = QtWidgets.QLineEdit(self.frame_2)
        self.equipEdit.setGeometry(QtCore.QRect(40, 220, 113, 20))
        self.equipEdit.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.equipEdit.setObjectName("equipEdit")
        self.roomEdit = QtWidgets.QLineEdit(self.frame_2)
        self.roomEdit.setGeometry(QtCore.QRect(210, 190, 101, 20))
        self.roomEdit.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.roomEdit.setObjectName("roomEdit")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(440, 0, 371, 601))
        self.frame.setStyleSheet("background-color: rgb(82, 175, 204);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(80, 160, 231, 41))
        self.label_5.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"color: rgb(240, 246, 247);")
        self.label_5.setObjectName("label_5")
        CadastrarLeito.setCentralWidget(self.centralwidget)

        self.retranslateUi(CadastrarLeito)
        QtCore.QMetaObject.connectSlotsByName(CadastrarLeito)

    def retranslateUi(self, CadastrarLeito):
        _translate = QtCore.QCoreApplication.translate
        CadastrarLeito.setWindowTitle(_translate("CadastrarLeito", "MainWindow"))
        self.cadasterButton.setText(_translate("CadastrarLeito", "Cadastrar"))
        self.goBackButton.setText(_translate("CadastrarLeito", "Voltar"))
        self.label.setText(_translate("CadastrarLeito", "N° Leito"))
        self.label_2.setText(_translate("CadastrarLeito", "N° Equipamento"))
        self.label_3.setText(_translate("CadastrarLeito", "Nome Quarto"))
        self.label_5.setText(_translate("CadastrarLeito", "Cadastre o Leito"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CadastrarLeito = QtWidgets.QMainWindow()
    ui = Ui_CadastrarLeito()
    ui.setupUi(CadastrarLeito)
    CadastrarLeito.show()
    sys.exit(app.exec_())
