# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(775, 381)
        MainWindow.setMinimumSize(QtCore.QSize(775, 381))
        MainWindow.setMaximumSize(QtCore.QSize(775, 381))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(390, 0, 411, 601))
        self.frame.setStyleSheet("background-color: rgb(82, 175, 204);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 341, 41))
        self.label_4.setStyleSheet("color: rgb(240, 246, 247);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 391, 601))
        self.frame_2.setStyleSheet("background-color: rgb(229, 238, 241);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.login = QtWidgets.QLineEdit(self.frame_2)
        self.login.setGeometry(QtCore.QRect(100, 80, 121, 20))
        self.login.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.login.setObjectName("login")
        self.entrarButton = QtWidgets.QPushButton(self.frame_2)
        self.entrarButton.setGeometry(QtCore.QRect(120, 180, 81, 31))
        self.entrarButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(82, 175, 204);\n"
"}")
        self.entrarButton.setObjectName("entrarButton")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(100, 60, 91, 16))
        self.label_2.setObjectName("label_2")
        self.newUserButton = QtWidgets.QPushButton(self.frame_2)
        self.newUserButton.setGeometry(QtCore.QRect(80, 250, 161, 41))
        self.newUserButton.setStyleSheet("QPushButton{\n"
"    border-radius: 20px;\n"
"    background-color: rgb(48, 50, 51);\n"
"    color: rgb(240, 246, 247);\n"
"}")
        self.newUserButton.setObjectName("newUserButton")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(100, 110, 91, 16))
        self.label_3.setObjectName("label_3")
        self.senha = QtWidgets.QLineEdit(self.frame_2)
        self.senha.setGeometry(QtCore.QRect(100, 130, 121, 20))
        self.senha.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senha.setObjectName("senha")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Controle Ocupacional Hospitalar"))
        self.entrarButton.setText(_translate("MainWindow", "Entrar"))
        self.label_2.setText(_translate("MainWindow", "Login"))
        self.newUserButton.setText(_translate("MainWindow", "Cadastrar novo usuário"))
        self.label_3.setText(_translate("MainWindow", "Senha"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
