# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Página Principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pagPrincipalWindow(object):
    def setupUi(self, pagPrincipalWindow):
        pagPrincipalWindow.setObjectName("pagPrincipalWindow")
        pagPrincipalWindow.resize(800, 600)
        pagPrincipalWindow.setMinimumSize(QtCore.QSize(800, 600))
        pagPrincipalWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(pagPrincipalWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-271, -1, 701, 601))
        self.frame_2.setStyleSheet("background-color: rgb(240, 246, 247);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.cadasterButton = QtWidgets.QPushButton(self.frame_2)
        self.cadasterButton.setGeometry(QtCore.QRect(310, 140, 141, 41))
        self.cadasterButton.setStyleSheet("background-color: rgb(82, 175, 204);\n"
"border: none;\n"
"")
        self.cadasterButton.setObjectName("cadasterButton")
        self.ctoButton = QtWidgets.QPushButton(self.frame_2)
        self.ctoButton.setGeometry(QtCore.QRect(310, 220, 141, 41))
        self.ctoButton.setStyleSheet("background-color: rgb(82, 175, 204);\n"
"border: none")
        self.ctoButton.setObjectName("ctoButton")
        self.endButton = QtWidgets.QPushButton(self.frame_2)
        self.endButton.setGeometry(QtCore.QRect(480, 220, 111, 41))
        self.endButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(48, 50, 51);\n"
"color: rgb(240, 246, 247);\n"
"border: none\n"
"}")
        self.endButton.setObjectName("endButton")
        self.cadLeitoButton = QtWidgets.QPushButton(self.frame_2)
        self.cadLeitoButton.setGeometry(QtCore.QRect(480, 140, 111, 41))
        self.cadLeitoButton.setStyleSheet("background-color: rgb(82, 175, 204);\n"
"border: none")
        self.cadLeitoButton.setObjectName("cadLeitoButton")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(290, 300, 381, 291))
        self.frame_3.setStyleSheet("background-color: rgb(48, 50, 51);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_2.setStyleSheet("color: rgb(240, 246, 247);")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(100, 10, 171, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(240, 246, 247);")
        self.lineEdit.setObjectName("lineEdit")
        self.findButton = QtWidgets.QPushButton(self.frame_3)
        self.findButton.setGeometry(QtCore.QRect(300, 10, 51, 21))
        self.findButton.setStyleSheet("background-color: rgb(82, 175, 204);\n"
"border: none\n"
"")
        self.findButton.setObjectName("findButton")
        self.nome = QtWidgets.QLabel(self.frame_3)
        self.nome.setGeometry(QtCore.QRect(20, 50, 271, 21))
        self.nome.setStyleSheet("color: rgb(255, 255, 255);")
        self.nome.setObjectName("nome")
        self.cpf = QtWidgets.QLabel(self.frame_3)
        self.cpf.setGeometry(QtCore.QRect(20, 100, 251, 21))
        self.cpf.setStyleSheet("color: rgb(255, 255, 255);")
        self.cpf.setObjectName("cpf")
        self.quarto = QtWidgets.QLabel(self.frame_3)
        self.quarto.setGeometry(QtCore.QRect(20, 150, 251, 21))
        self.quarto.setStyleSheet("color: rgb(255, 255, 255);")
        self.quarto.setObjectName("quarto")
        self.delete_2 = QtWidgets.QPushButton(self.frame_3)
        self.delete_2.setGeometry(QtCore.QRect(20, 240, 75, 23))
        self.delete_2.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.delete_2.setObjectName("delete_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(430, 0, 611, 601))
        self.frame.setStyleSheet("background-color: rgb(82, 175, 204);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(110, 200, 171, 41))
        self.label.setStyleSheet("color: rgb(240, 246, 247);\n"
"font: 22pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        pagPrincipalWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(pagPrincipalWindow)
        QtCore.QMetaObject.connectSlotsByName(pagPrincipalWindow)

    def retranslateUi(self, pagPrincipalWindow):
        _translate = QtCore.QCoreApplication.translate
        pagPrincipalWindow.setWindowTitle(_translate("pagPrincipalWindow", "MainWindow"))
        self.cadasterButton.setText(_translate("pagPrincipalWindow", "Cadastrar Pacientes"))
        self.ctoButton.setText(_translate("pagPrincipalWindow", "Consultar Taxa de Ocupação"))
        self.endButton.setText(_translate("pagPrincipalWindow", "Encerrar"))
        self.cadLeitoButton.setText(_translate("pagPrincipalWindow", "Cadastrar Leitos"))
        self.label_2.setText(_translate("pagPrincipalWindow", "Digite um CPF"))
        self.findButton.setText(_translate("pagPrincipalWindow", "Pesquisar"))
        self.nome.setText(_translate("pagPrincipalWindow", "Nome"))
        self.cpf.setText(_translate("pagPrincipalWindow", "cpf"))
        self.quarto.setText(_translate("pagPrincipalWindow", "quarto"))
        self.delete_2.setText(_translate("pagPrincipalWindow", "Delete"))
        self.label.setText(_translate("pagPrincipalWindow", "Página Inicial"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pagPrincipalWindow = QtWidgets.QMainWindow()
    ui = Ui_pagPrincipalWindow()
    ui.setupUi(pagPrincipalWindow)
    pagPrincipalWindow.show()
    sys.exit(app.exec_())
