# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Taxa de Ocupação.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaxaOcupacao(object):
    def setupUi(self, TaxaOcupacao):
        TaxaOcupacao.setObjectName("TaxaOcupacao")
        TaxaOcupacao.resize(800, 419)
        TaxaOcupacao.setMinimumSize(QtCore.QSize(800, 419))
        TaxaOcupacao.setMaximumSize(QtCore.QSize(800, 419))
        self.centralwidget = QtWidgets.QWidget(TaxaOcupacao)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(430, -10, 371, 601))
        self.frame.setStyleSheet("background-color: rgb(82, 175, 204);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 170, 201, 31))
        self.label.setStyleSheet("color: rgb(240, 246, 247);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-11, -11, 441, 611))
        self.frame_2.setStyleSheet("background-color: rgb(240, 246, 247);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(70, 90, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(220, 90, 131, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(70, 150, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(220, 150, 131, 20))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(180, 230, 51, 20))
        self.label_8.setObjectName("label_8")
        self.goBackButton = QtWidgets.QPushButton(self.frame_2)
        self.goBackButton.setGeometry(QtCore.QRect(155, 310, 91, 41))
        self.goBackButton.setStyleSheet("QPushButton{\n"
"    border-radius: 20px;\n"
"    background-color: rgb(48, 50, 51);\n"
"    color: rgb(240, 246, 247);\n"
"}")
        self.goBackButton.setObjectName("goBackButton")
        self.numLeitoEdit = QtWidgets.QLineEdit(self.frame_2)
        self.numLeitoEdit.setEnabled(False)
        self.numLeitoEdit.setGeometry(QtCore.QRect(70, 110, 113, 20))
        self.numLeitoEdit.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.numLeitoEdit.setObjectName("numLeitoEdit")
        self.numEquipEdit = QtWidgets.QLineEdit(self.frame_2)
        self.numEquipEdit.setEnabled(False)
        self.numEquipEdit.setGeometry(QtCore.QRect(220, 110, 113, 20))
        self.numEquipEdit.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.numEquipEdit.setObjectName("numEquipEdit")
        self.numPacientesEdit = QtWidgets.QLineEdit(self.frame_2)
        self.numPacientesEdit.setEnabled(False)
        self.numPacientesEdit.setGeometry(QtCore.QRect(70, 170, 113, 20))
        self.numPacientesEdit.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.numPacientesEdit.setObjectName("numPacientesEdit")
        self.numOcupEdit = QtWidgets.QLineEdit(self.frame_2)
        self.numOcupEdit.setEnabled(False)
        self.numOcupEdit.setGeometry(QtCore.QRect(220, 170, 113, 20))
        self.numOcupEdit.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.numOcupEdit.setObjectName("numOcupEdit")
        self.situacaoEdit = QtWidgets.QLineEdit(self.frame_2)
        self.situacaoEdit.setEnabled(False)
        self.situacaoEdit.setGeometry(QtCore.QRect(145, 250, 113, 20))
        self.situacaoEdit.setStyleSheet("background-color: rgb(198, 209, 212);")
        self.situacaoEdit.setObjectName("situacaoEdit")
        TaxaOcupacao.setCentralWidget(self.centralwidget)

        self.retranslateUi(TaxaOcupacao)
        QtCore.QMetaObject.connectSlotsByName(TaxaOcupacao)

    def retranslateUi(self, TaxaOcupacao):
        _translate = QtCore.QCoreApplication.translate
        TaxaOcupacao.setWindowTitle(_translate("TaxaOcupacao", "MainWindow"))
        self.label.setText(_translate("TaxaOcupacao", "Taxa de Ocupação"))
        self.label_2.setText(_translate("TaxaOcupacao", "Número de Leitos"))
        self.label_3.setText(_translate("TaxaOcupacao", "Número de Equipamentos"))
        self.label_4.setText(_translate("TaxaOcupacao", "Número de Pacientes"))
        self.label_5.setText(_translate("TaxaOcupacao", "Porcentagem de Ocupação"))
        self.label_8.setText(_translate("TaxaOcupacao", "Situação"))
        self.goBackButton.setText(_translate("TaxaOcupacao", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TaxaOcupacao = QtWidgets.QMainWindow()
    ui = Ui_TaxaOcupacao()
    ui.setupUi(TaxaOcupacao)
    TaxaOcupacao.show()
    sys.exit(app.exec_())
